name: "Create Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    name: Create tagged release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Set env (MAC)
        if: matrix.os == 'macos-latest'
        uses: lukka/set-shell-env@v1.1
        with:
          tag_version: ${GITHUB_REF/refs\/tags\/v/}
          tag_version_with_v: ${GITHUB_REF/refs\/tags\/}

      - name: Set env for (Windows)
        if: matrix.os == 'windows-latest'
        uses: lukka/set-shell-env@v1.1
        with:
          tag_version: $env:GITHUB_REF.replace('refs/tags/v','')
          tag_version_with_v: $env:GITHUB_REF.replace('refs/tags/','')

      - name: Download aspect model service into project (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir backend
          echo ${{ tag_version }}
          echo ${{ tag_version_with_v }}

          ASSET_ONE_URL=$(curl -sl --header "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" https://api.github.com/repos/bci-oss/rbs-aspect-model-service/releases/tags/${{ tag_version_with_v }} | jq '.assets[0].browser_download_url')
          ASSET_TWO_URL=$(curl -sl --header "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" https://api.github.com/repos/bci-oss/rbs-aspect-model-service/releases/tags/${{ tag_version_with_v }} | jq '.assets[1].browser_download_url')

          if [[ ${ASSET_ONE_URL} != *".exe"* ]];
            then
              echo $ASSET_ONE_URL
              DOWNLOAD_URL=$(curl -sl --header "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" https://api.github.com/repos/bci-oss/rbs-aspect-model-service/releases/tags/${{ tag_version_with_v }} | jq -r '.assets[0].url')
          fi

          if [[ ${ASSET_TWO_URL} != *".exe"* ]];
            then
              echo $ASSET_TWO_URL
              DOWNLOAD_URL=$(curl -sl --header "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" https://api.github.com/repos/bci-oss/rbs-aspect-model-service/releases/tags/${{ tag_version_with_v }} | jq -r '.assets[1].url')
          fi

          curl -L -H "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" -H "Accept: application/octet-stream" $DOWNLOAD_URL > backend/ame-backend.sh
          chmod 755 backend/ame-backend.sh

      - name: Download aspect model service into project (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir backend
          echo ${{ env:tag_version }}
          echo $${{ env:tag_version_with_v }}

          $RESPONSE=$(curl.exe -sl --header "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" https://api.github.com/repos/bci-oss/rbs-aspect-model-service/releases/tags/${{ env:tag_version_with_v }}
          $RESPONSE_JSON=($RESPONSE | ConvertFrom-Json)

          if ($RESPONSE_JSON.assets[0].browser_download_url -match ".exe") {
            echo $RESPONSE_JSON.assets[0].browser_download_url
            curl.exe -sL -H "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" -H "Accept: application/octet-stream" $RESPONSE_JSON.assets[0].url -o backend/ame-backend.exe
          } elseif ($RESPONSE_JSON.assets[1].browser_download_url -match ".exe") {
            echo $RESPONSE_JSON.assets[1].browser_download_url
            curl.exe -sL -H "Authorization: token ${{ secrets.RBS_BOT_TOKEN }}" -H "Accept: application/octet-stream" $RESPONSE_JSON.assets[1].url -o backend/ame-backend.exe
          }

      - name: Install node modules
        run: npm install
        working-directory: core

      - name: Set app version (Mac)
        if: matrix.os == 'macos-latest'
        run: npm version ${{ tag_version }}
        working-directory: core

      - name: Set app version (Windows)
        if: matrix.os == 'windows-latest'
        run: npm version ${{ env:tag_version }}
        working-directory: core

      - name: Build electron app (Mac)
        if: matrix.os == 'macos-latest'
        run: npm run electron-builder-mac-prod
        working-directory: core

      - name: Build electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run electron-builder-win-prod
        working-directory: core

      - name: Create Windows installer
        if: matrix.os == 'windows-latest'
        uses: joncloud/makensis-action@v3.6
        with:
          script-file: win-installer/installer.nsi
          arguments: "-V3 -DVERSION=${{ env.tag_version }}"

      - name: Create GitHub release (Mac)
        if: ${{ (matrix.os == 'macos-latest') &&  (!contains( github.ref, '-M' )) }}
        uses: svenstaro/upload-release-action@latest
        with:
          overwrite: true
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: core/electron/aspect-model-editor-${{ tag_version }}-mac.dmg
          tag: ${{ github.ref }}

      - name: Create GitHub pre-release (Mac)
        if: ${{ (matrix.os == 'macos-latest') &&  (contains( github.ref, '-M' )) }}
        uses: svenstaro/upload-release-action@latest
        with:
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: core/electron/aspect-model-editor-${{ tag_version }}.dmg
          tag: ${{ github.ref }}

      - name: Create GitHub release (Windows)
        if: ${{ (matrix.os == 'windows-latest') && (!contains( github.ref, '-M' )) }}
        uses: svenstaro/upload-release-action@latest
        with:
          overwrite: true
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: win-installer/aspect-model-editor-${{ env.tag_version }}-win.exe
          tag: ${{ github.ref }}

      - name: Create GitHub pre-release (Windows)
        if: ${{ (matrix.os == 'windows-latest') && (contains( github.ref, '-M' )) }}
        uses: svenstaro/upload-release-action@latest
        with:
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: win-installer/aspect-model-editor-${{ env.tag_version }}-win.exe
          tag: ${{ github.ref }}
